# environment.yml

name: python-video-annotator-env # this is just a name for the environment
dependencies:
  - sphinx_bootstrap_theme
  - python=2.7
  - pyqt=4
  - numpy
  - pip:
      - sphinx
      - recommonmark
      - https://bitbucket.org/fchampalimaud/logging-bootstrap/get/master.zip